---

# add any keys to ../../files/authorized_keys
- name: add keys to authorized_keys
  authorized_key:
    user: "{{ remoteUser }}"
    key: "{{ lookup('file', '{{ remoteUser }}_pubkey') }}"

- name: Insert/Update "Match User" configuration block in /etc/ssh/sshd_config prepending and appending a new line
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User {{ remoteUser }}
          AuthenticationMethods publickey
          PasswordAuthentication no
  become: yes
  
- name: restart service sshd
  ansible.builtin.systemd_service:
    name: sshd.service
    state: restarted
  become: yes
 

 